# docker-compose up -d
#
# https://grafana.com/docs/installation/docker/
# https://hub.docker.com/_/influxdb/


version: "2"

services:
  nodered:
    build: ./nodered
#    image: nodered/node-red
    restart: unless-stopped
    volumes:
      - ./nodered:/data
    ports:
      - 1880:1880
    environment:
      - TZ=Europe/Stockholm
#    depends_on:
#      - influxdb
  
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=home
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true

volumes:
  grafana_data:
  influxdb_data:
