{
 "title": "InfluxDB Internals",
 "description": "InfluxDB internal metrics display",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "InfluxDB Metric Database", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " SELECT sum(last) FROM (SELECT last(diskBytes) FROM \"shard\" GROUP BY \"id\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Databases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " SELECT count(last) FROM (SELECT last(numMeasurements) FROM \"database\" GROUP BY \"database\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measurements",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " SELECT sum(last) FROM (SELECT last(numMeasurements) FROM \"database\" GROUP BY \"database\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Series",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " SELECT sum(last) FROM (SELECT last(numSeries) FROM \"database\" GROUP BY \"database\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Points",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " SELECT sum(last) FROM (SELECT last(writePointsOk) FROM \"shard\" GROUP BY \"id\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "DATABASE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "databse",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "database" ], "type": "tag" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "numSeries" ], "type": "alias" }
      ],
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "numMeasurements" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "shards",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 7, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "retentionPolicy" ], "type": "tag" }
     ],
     "measurement": "shard",
     "query": "SELECT sum(\"last\") AS \"Bytes\", count(\"last\") AS \"count\" FROM (SELECT last(\"diskBytes\") FROM \"shard\" WHERE $timeFilter GROUP BY \"database\",\"id\",\"retentionPolicy\") GROUP BY \"database\",\"retentionPolicy\"\n",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Point Intake",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenFail\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenOK\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "InfluxDB Data Caching Composition",
     "type": "table",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "tsm1_cache",
       "select": [
        [
         { "params": [ "diskBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "diskBytes" ], "type": "alias" }
        ],
        [
         { "params": [ "memBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "memBytes" ], "type": "alias" }
        ],
        [
         { "params": [ "cachedBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "cachedBytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "CentDevT1A" }
       ]
      }
     ]
    },
    {
     "title": "InfluxDB Heap Usage : stats-node-0",
     "type": "graph",
     "gridPos": { "h": 13, "w": 16, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "MB" }
     ],
     "targets": [
      {
       "alias": "influx-0 $col",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "runtime",
       "select": [
        [
         { "params": [ "HeapInUse" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [
           10
          ],
          "type": "moving_average"
         },
         { "params": [ "heap active" ], "type": "alias" }
        ],
        [
         { "params": [ "HeapIdle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [
           10
          ],
          "type": "moving_average"
         },
         { "params": [ "heap idle" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "CentDevT1A" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "Client Errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(last(\"clientError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Server Errors",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(last(\"serverError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}